version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test

permissions:
   - object: /home/ec2-user/test
     pattern: "**"
     mode: 777
     type:
       - file

hooks:
  ApplicationInstall:
     - location: home/ec2-user/aa.sh
       runas: root
