version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test

permissions:
   - object: /home/ec2-user/test
     pattern: "**"
     mode: 755
     type:
       - file

hooks:
  AfterInstall:
     - location: /home/ec2-user/aa.sh
       runas: root
  ApplicationInstall:
     - location: scripts/aa.sh
       runas: root
